name: Daily Auto Commit

on:
  schedule:
    - cron: '24 3 * * *'  # Runs daily at 06:17 UTC (~11:47 AM IST)
  workflow_dispatch:     # Allows manual trigger as well

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp - 23f3001359@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date -u)" > .last-updated.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .last-updated.txt
          git commit -m "Daily update at $(date -u)"
          git push
